In [1]:
import numpy as np
import pandas as pd
from tqdm import tqdm
import math

from keras.preprocessing.text import *
from keras.preprocessing.sequence import skipgrams, pad_sequences

Using TensorFlow backend.


In [55]:
import keras.backend as K
import tensorflow as tf
import math as math

y_true = np.array([[0, 0, 0], [1, 1, 0], [0, 1, 0], [0, 0, 0]])
y_pred = np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0], [0, 0, 1]])

y_pred = np.clip(y_pred, e, 1 - e)

e = 0.0000001
result = []
for i in range(len(y_pred)):
    y_pred_i = np.clip(y_pred[i], e, 1-e)
    print(y_pred_i)
    result.append(-np.mean([y_true[i][j] * math.log(y_pred_i[j]) + (1 - y_true[i][j]) * math.log(1 - y_pred_i[j]) for j in range(len(y_pred_i))]))
np.mean(result)

[  1.00000000e-07   1.00000000e-07   1.00000000e-07]
[  1.00000000e-07   9.99999900e-01   1.00000000e-07]
[  1.00000000e-07   1.00000000e-07   1.00000000e-07]
[  1.00000000e-07   1.00000000e-07   9.99999900e-01]


4.0295239877834463

In [56]:
import keras.backend as K
import tensorflow as tf
import math as math

print(y_true)
print(' ')
print(y_pred)
print('')


o_terms = np.multiply(y_true, np.log(y_pred))
z_terms = np.multiply(np.subtract(1, y_true), np.log(np.subtract(1, y_pred)))

print(o_terms)
print(' ')
print(z_terms)

o_result = []
for i in range(len(y_pred)):
    o_result.append([y_true[i][j] * math.log(y_pred[i][j]) for j in range(len(y_pred[i]))])
#print(np.array(o_result))

z_result = []
for i in range(len(y_pred)):
    z_result.append([(1 - y_true[i][j]) * math.log(1 - y_pred[i][j]) for j in range(len(y_pred[i]))])
#print(np.array(z_result))

terms = np.add(o_terms, z_terms)
terms = np.negative(np.mean(terms))

np.mean(terms)

[[0 0 0]
 [1 1 0]
 [0 1 0]
 [0 0 0]]
 
[[  1.00000000e-09   1.00000000e-09   1.00000000e-09]
 [  1.00000000e-09   9.99999999e-01   1.00000000e-09]
 [  1.00000000e-09   1.00000000e-09   1.00000000e-09]
 [  1.00000000e-09   1.00000000e-09   9.99999999e-01]]

[[ -0.00000000e+00  -0.00000000e+00  -0.00000000e+00]
 [ -1.61180957e+01  -1.00000005e-07  -0.00000000e+00]
 [ -0.00000000e+00  -1.61180957e+01  -0.00000000e+00]
 [ -0.00000000e+00  -0.00000000e+00  -0.00000000e+00]]
 
[[ -1.00000005e-07  -1.00000005e-07  -1.00000005e-07]
 [ -0.00000000e+00  -0.00000000e+00  -1.00000005e-07]
 [ -1.00000005e-07  -0.00000000e+00  -1.00000005e-07]
 [ -1.00000005e-07  -1.00000005e-07  -1.61180957e+01]]


4.0295239877834481

In [60]:
import keras.backend as K
import tensorflow as tf
import math as math

print(y_true)
print(' ')
print(y_pred)
print('')

o_weight = np.array([2, 3, 3])
o_terms = np.multiply(np.multiply(y_true, np.log(y_pred)), o_weight)
z_terms = np.multiply(np.subtract(1, y_true), np.log(np.subtract(1, y_pred)))

print(o_terms)
print(' ')
print(z_terms)

o_result = []
for i in range(len(y_pred)):
    o_result.append([y_true[i][j] * math.log(y_pred[i][j]) for j in range(len(y_pred[i]))])
#print(np.array(o_result))

z_result = []
for i in range(len(y_pred)):
    z_result.append([(1 - y_true[i][j]) * math.log(1 - y_pred[i][j]) for j in range(len(y_pred[i]))])
#print(np.array(z_result))

terms = np.add(o_terms, z_terms)
terms = np.negative(np.mean(terms))

np.mean(terms)


[[0 0 0]
 [1 1 0]
 [0 1 0]
 [0 0 0]]
 
[[  1.00000000e-07   1.00000000e-07   1.00000000e-07]
 [  1.00000000e-07   9.99999900e-01   1.00000000e-07]
 [  1.00000000e-07   1.00000000e-07   1.00000000e-07]
 [  1.00000000e-07   1.00000000e-07   9.99999900e-01]]

[[ -0.00000000e+00  -0.00000000e+00  -0.00000000e+00]
 [ -3.22361913e+01  -3.00000015e-07  -0.00000000e+00]
 [ -0.00000000e+00  -4.83542870e+01  -0.00000000e+00]
 [ -0.00000000e+00  -0.00000000e+00  -0.00000000e+00]]
 
[[ -1.00000005e-07  -1.00000005e-07  -1.00000005e-07]
 [ -0.00000000e+00  -0.00000000e+00  -1.00000005e-07]
 [ -1.00000005e-07  -0.00000000e+00  -1.00000005e-07]
 [ -1.00000005e-07  -1.00000005e-07  -1.61180957e+01]]


8.0590479171896963

In [45]:
math.log(0.00000000000001)

-32.23619130191664

In [ ]:
categories = ['toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate']

df_train = pd.read_csv('input/train.csv')

x_train = df_train['comment_text']
y_train = df_train[categories].as_matrix()

display(df_train.head())
m = x_train.shape[0]
display(f'total m = {m}')

tokenizer = Tokenizer(lower=True)
tokenizer.fit_on_texts(texts=x_train)

vocabulary_size = len(tokenizer.word_index)
sequences = tokenizer.texts_to_sequences(texts=x_train)

max_seq_len = 0
for sequence in sequences:
    max_seq_len = max(max_seq_len, len(sequence))

print('max length {}'.format(max_seq_len))

In [ ]:
from keras.models import Sequential
from keras.layers import Dense, Activation, Embedding, Flatten
from keras.metrics import categorical_accuracy

embedding_dim = 50
weights = np.load('output/embedding_weights_20180312.npy')

embedding = Embedding(vocabulary_size + 1, embedding_dim, weights=weights, trainable=False)

from keras.layers import Bidirectional, LSTM, GRU, Dense

import keras.backend as K

toxic_weighting = 2.0

import tensorflow as tf

def custom_binary_crossentropy(target, output, from_logits=True):
    target_bool = tf.equal(target, 0, name='target_boolean')
    bool_filter = tf.reduce_all(target_bool, axis=1, name='boolean_filter')
    
    non_toxics = tf.boolean_mask(target, bool_filter, name='non_toxics')
    non_toxics_output = tf.boolean_mask(output, bool_filter, name='non_toxics_output')
    non_toxics_result = K.binary_crossentropy(non_toxics, non_toxics_output)
#     print('non_toxics_result: {}'.format(non_toxics_result))
    
    toxics = tf.boolean_mask(target, ~bool_filter, name='toxics')
    toxics_output = tf.boolean_mask(output, ~bool_filter, name='toxics_output')
    toxics_result = K.binary_crossentropy(toxics, toxics_output)
#     print('toxic_result {}'.format(toxics_result))
#     weighted_toxics_result = toxics_result * toxic_weighting
#     print('weighted_toxic_result {}'.format(weighted_toxics_result))
#     print ('sum {}'.format((non_toxics_result + toxics_result)))
#     print ('weighted sum {}'.format((non_toxics_result + weighted_toxics_result)))

    return K.mean(non_toxics_result) + (K.mean(toxics_result) * toxic_weighting)

def init_weighted_binary_crossentropy(zero_weight, one_weight):

    def weight_binary_crossentropy(y_true, y_pred):
        b_ce = K.binary_crossentropy(y_true, y_pred)

        # Apply the weights
        weight_vector = (y_true * one_weight) + ((1. - y_true) * zero_weight)
        weighted_b_ce = weight_vector * b_ce

        # Return the mean error
        return K.mean(weighted_b_ce)
    
    return weight_binary_crossentropy

input_model = Sequential()
input_model.add(embedding)
input_model.add(GRU(32))
input_model.add(Dense(6, activation='sigmoid'))

input_model.compile(optimizer='adam', loss=init_weighted_binary_crossentropy(0.001, 2), metrics=[categorical_accuracy])

In [ ]:
y_true = np.array([[0,0,0], [0, 1, 0], [1, 0, 0]])
weighted = (y_true) * 2 + (1. - y_true) * 0.0000001
print(weighted)

In [ ]:
batch_size = 3072

def inputs():
    padded_sequences = pad_sequences(sequences=sequences, maxlen=max_seq_len, padding='post')
    x_list = []
    y_list = []
    for sequence, y_train_val in zip(padded_sequences, y_train):
        x_list.append(sequence)
        y_list.append(y_train_val)
    return np.array(x_list), np.array(y_list)

x_inputs, y_inputs = inputs()

hist = input_model.fit(x=x_inputs, y=y_inputs, epochs=6, batch_size=batch_size)

print(hist.history.items())


In [ ]:
y_pred = input_model.predict(x=x_inputs)

In [ ]:
display(y_pred)

y_pred_labels = np.zeros((y_pred.shape[0], y_pred.shape[1]))

for i in range(len(categories)):
    y_pred_labels[y_pred[:,i] > 0.5, i] = 1

In [ ]:
display(y_pred_labels)


In [ ]:
from sklearn.metrics import accuracy_score

accuracy_score(y_train, y_pred_labels)

In [65]:
math.log()

-52.95945713886305